import pyautogui
pyautogui.FAILSAFE = False
import time
# time.sleep(2)
pyautogui.hotkey('win','d')
# pyautogui.moveTo(670,300)
# pyautogui.click(button='left')
# pyautogui.hotkey('alt', 'f4')
# pyautogui.hotkey('win', 'r')
# pyautogui.moveTo(1270, 0)
# pyautogui.click(button='left')
# time.sleep(2)
# pyautogui.click(button='left')
pyautogui.moveTo(0, 50)
time.sleep(1)
pyautogui.click(button='right')
pyautogui.moveTo(10, 60)
time.sleep(1)
pyautogui.click(button='right')
pyautogui.moveTo(300, 300)
time.sleep(1)
pyautogui.click(button='left')
time.sleep(1)
pyautogui.click(button='right')
pyautogui.moveTo(250, 290)
time.sleep(1)
pyautogui.click(button='right')
pyautogui.moveTo(400, 150)
time.sleep(1)
pyautogui.click(button='left')
time.sleep(1)
pyautogui.click(button='right')
pyautogui.moveTo(30,160)
time.sleep(1)
pyautogui.click(button='right')
pyautogui.moveTo(400,500)
time.sleep(1)
pyautogui.click(button='right')
pyautogui.moveTo(320,387)
time.sleep(1)
pyautogui.click(button='right')
time.sleep(1)
pyautogui.moveTo(500,750)
time.sleep(1)
pyautogui.moveTo(510,600)
pyautogui.click(button='left')
pyautogui.click(button='right')
pyautogui.moveTo(1250,50)
# pyautogui.click(button='left')
# pyautogui.click(button='right')
# pyautogui.hotkey('win','up')
# time.sleep(1)
# pyautogui.moveTo(600,650)
# time.sleep(1)
# pyautogui.moveTo(600,650)
# time.sleep(1)
# pyautogui.moveTo(550,650)





