import pyautogui
import time
pyautogui.FAILSAFE = False
time.sleep(2)
pyautogui.moveTo(1270, 0)
pyautogui.click(button='left')
time.sleep(2)
pyautogui.click(button='left')
pyautogui.moveTo(0, 50)
time.sleep(2)
pyautogui.click(button='right')
pyautogui.moveTo(10, 60)
time.sleep(2)
pyautogui.click(button='right')
pyautogui.moveTo(300, 300)
time.sleep(2)
pyautogui.click(button='left')
time.sleep(2)
pyautogui.click(button='right')
pyautogui.moveTo(250, 290)
time.sleep(2)
pyautogui.click(button='right')
pyautogui.moveTo(400, 150)
time.sleep(2)
pyautogui.click(button='left')
time.sleep(2)
pyautogui.click(button='right')
pyautogui.moveTo(30,160)
time.sleep(2)
pyautogui.click(button='right')
pyautogui.moveTo(400,500)
time.sleep(2)
pyautogui.click(button='right')
pyautogui.moveTo(320,387)
time.sleep(2)
pyautogui.click(button='right')


